name: Build LOS19(Android12) MSM8974
on:
  workflow_dispatch: # 手动触发，手机点按钮就能编译
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 配置环境与依赖
        run: |
          sudo apt update && sudo apt install -y git python3 python3-pip zip unzip curl repo libncurses5-dev
          git config --global user.name "GithubCI"
          git config --global user.email "ci@github.com"
      - name: 拉取LineageOS源码
        run: |
          mkdir los && cd los
          repo init -u https://github.com/LineageOS/android.git -b lineage-19.1
          repo sync -j$(nproc)
      - name: 克隆公共设备树 msm8974-common
        run: |
          cd los/device/xiaomi
          git clone https://github.com/rlightz7if/android_device_xiaomi_msm8974-common msm8974-common
      - name: 克隆内核
        run: |
          cd los/kernel/xiaomi
          # 小米4 Cancro 使用这条
          git clone https://github.com/rlightz7if/kernel_xiaomi_cancro cancro
          # 小米3/小米Note标准版注释上面，启用下面安卓11内核链接
          # git clone 安卓11内核地址 cancro
      - name: 编译小米4(cancro) LOS
        run: |
          cd los
          source build/envsetup.sh
          lunch lineage_cancro-userdebug
          make -j$(nproc) bacon
      - name: 上传编译成品刷机包
        uses: actions/upload-artifact@v4
        with:
          name: LOS19-Cancro-ROM
          path: los/out/target/product/cancro/*.zip
