name: Build LOS19(Android12) MSM8974
on:
  workflow_dispatch: # 手动触发
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 配置环境依赖 + 本地repo规避权限问题
       run: |
          sudo apt update && sudo apt install -y git python3 python3-pip zip unzip curl libncurses5-dev
          git config --global user.name "GithubCI"
          git config --global user.email "ci@github.com"
          # 不用系统repo，下载到家目录
          curl https://mirrors.tuna.tsinghua.edu.cn/git/git-repo -o ~/repo
          chmod +x ~/repo
          echo "export PATH=\$HOME:\$PATH" >> ~/.bashrc
          source ~/.bashrc
          # 配置repo镜像加速（可选，解决国外同步慢）
          echo "export REPO_URL='https://mirrors.tuna.tsinghua.edu.cn/git/git-repo'" >> ~/.bashrc
          source ~/.bashrc

      - name: 拉取LineageOS源码
        run: |
          mkdir los && cd los
          repo init -u https://github.com/LineageOS/android.git -b lineage-19.1
          repo sync -j$(nproc)

      - name: 克隆公共设备树 msm8974-common
        run: |
          mkdir -p los/device/xiaomi
          cd los/device/xiaomi
          git clone https://github.com/rlightz7if/android_device_xiaomi_msm8974-common msm8974-common

      - name: 克隆内核
        run: |
          mkdir -p los/kernel/xiaomi
          cd los/kernel/xiaomi
          # 小米4 Cancro
          git clone https://github.com/rlightz7if/kernel_xiaomi_cancro cancro
          # 小米3/Note 取消注释切换内核
          # git clone 安卓11内核地址 cancro

      - name: 编译小米4(cancro) LOS
        run: |
          cd los
          source build/envsetup.sh
          lunch lineage_cancro-userdebug
          make -j$(nproc) bacon

      - name: 上传编译成品刷机包
        uses: actions/upload-artifact@v4
        with:
          name: LOS19-Cancro-ROM
          path: los/out/target/product/cancro/*.zip
